apiVersion: v1
kind: ConfigMap
metadata:
  name: gha-pc-dae-infra-resourcemanager-config
  namespace: flux-system
data:
  runner_org: pc-dae
  runner_repo: infra-resourcemanager
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gha-pc-dae-infra-resourcemanager
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 30s
  timeout: 30s
  dependsOn:
    - name: gha-controller
  path: ./mgmt-cluster/addons/gha-runners/runner/flux
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: global-config
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
      - kind: ConfigMap
        name: gha-pc-dae-infra-resourcemanager-config