apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  dependsOn:
  - name: flux-components
  interval: 10m0s
  retryInterval: 30s
  timeout: 30s
  path: ./mgmt-cluster/addons/cert-manager
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: global-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx
  namespace: flux-system
spec:
  dependsOn:
  - name: flux-components
  interval: 10m0s
  retryInterval: 30s
  timeout: 30s
  path: ./mgmt-cluster/addons/nginx
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: global-config
  postBuild:
    substitute:
      dnsSuffix: dell.kubernetes.docker.internal
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-config
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 30s
  timeout: 30s
  path: ./mgmt-cluster/cert-config
  prune: true
  wait: true
  dependsOn:
    - name: cert-manager
    - name: nginx
  sourceRef:
    kind: GitRepository
    name: global-config
  postBuild:
    substitute:
      dnsSuffix: dell.kubernetes.docker.internal
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vault
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-config
    - name: config
  interval: 10m0s
  retryInterval: 30s
  timeout: 30s
  path: ./mgmt-cluster/addons/vault
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: global-config
  postBuild:
    substitute:
      storageClass: hostpath
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  dependsOn:
  - name: flux-components
  interval: 10m0s
  retryInterval: 30s
  timeout: 30s
  path: ./mgmt-cluster/addons/external-secrets
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: global-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secrets
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 30s
  timeout: 30s
  path: ./mgmt-cluster/secrets
  prune: true
  wait: true
  dependsOn:
    - name: external-secrets
    - name: cert-config
    - name: vault
  sourceRef:
    kind: GitRepository
    name: global-config
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dex
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 30s
  timeout: 30s
  dependsOn:
    - name: vault
    - name: secrets
    - name: config
  path: ./mgmt-cluster/addons/dex
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: global-config
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: config
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 30s
  timeout: 30s
  path: ./mgmt-cluster/config
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 30s
  timeout: 30s
  dependsOn:
    - name: dex
  path: ./mgmt-cluster/bases/flux
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: global-config
  postBuild:
    substituteFrom:
      - kind: ConfigMap
       name: cluster-config
