apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: config
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 30s
  timeout: 30s
  path: ./mgmt-cluster/config
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
