---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: harbor
  namespace: flux-system
spec:
  dependsOn:
  - name: nginx
  interval: 10m0s
  retryInterval: 30s
  timeout: 30s
  path: ./mgmt-cluster/addons/harbor
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: global-config
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
